name: Docker Deploy

on:
  workflow_run:
    workflows: ["Backend CI/CD", "Frontend CI/CD"]
    types:
      - completed
    branches: [main]

jobs:
  deploy:
    name: Deploy with Docker
    runs-on: ubuntu-latest
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      
      - name: Build and push backend image
        uses: docker/build-push-action@v5
        with:
          context: ./backend
          push: true
          tags: ${{ secrets.DOCKER_USERNAME }}/kiwey-backend:latest,${{ secrets.DOCKER_USERNAME }}/kiwey-backend:${{ github.sha }}
          cache-from: type=registry,ref=${{ secrets.DOCKER_USERNAME }}/kiwey-backend:buildcache
          cache-to: type=registry,ref=${{ secrets.DOCKER_USERNAME }}/kiwey-backend:buildcache,mode=max
      
      - name: Build and push frontend image
        uses: docker/build-push-action@v5
        with:
          context: ./frontend
          push: true
          tags: ${{ secrets.DOCKER_USERNAME }}/kiwey-frontend:latest,${{ secrets.DOCKER_USERNAME }}/kiwey-frontend:${{ github.sha }}
          cache-from: type=registry,ref=${{ secrets.DOCKER_USERNAME }}/kiwey-frontend:buildcache
          cache-to: type=registry,ref=${{ secrets.DOCKER_USERNAME }}/kiwey-frontend:buildcache,mode=max
      
      # Nếu triển khai tới server Linux (ví dụ VPS)
      - name: Deploy to server
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USERNAME }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          port: ${{ secrets.SSH_PORT }}
          script: |
            cd /path/to/deployment
            
            # Backup docker-compose file nếu cần
            cp docker-compose.yml docker-compose.yml.backup
            
            # Download docker-compose mới nhất từ repository
            wget -O docker-compose.yml https://raw.githubusercontent.com/${{ github.repository }}/main/docker-compose.yml
            
            # Update docker images
            docker pull ${{ secrets.DOCKER_USERNAME }}/kiwey-backend:latest
            docker pull ${{ secrets.DOCKER_USERNAME }}/kiwey-frontend:latest
            
            # Khởi động lại các container
            docker-compose down
            docker-compose up -d
            
            # Dọn dẹp old images
            docker image prune -af
            
            echo "Deployment completed successfully"